#!/bin/bash

# official void-packages template:
# https://github.com/void-linux/void-packages/blob/master/srcpkgs/spotify/template

pkgname='spotify'
version='1.1.84'
commit='716.gc5f8b819-2'
revision='2'
arch='x86_64'

depends=('libcurl>=7.86.0')

short_desc='Proprietary music streaming client'
license='Proprietary'
homepage='https://www.spotify.com'

prepare() {
  # downloads bundle
  [ -f "${srcdir}/bundle.deb" ] || curl \
    -o "${srcdir}/bundle.deb" \
    -L "http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_${version}.${commit}_amd64.deb"

  # extract bundle
  [ -f "${srcdir}/bundle.tar.gz" ] || ar p \
    "${srcdir}/bundle.deb" 'data.tar.gz' > "${srcdir}/bundle.tar.gz"
}

package() {
  tar --extract -C "${pkgdir}" -vf "${srcdir}/bundle.tar.gz"

  mkdir -p "${pkgdir}/usr/share/applications"
  mv "${pkgdir}/usr/share/spotify/spotify.desktop" \
    "${pkgdir}/usr/share/applications/spotify.desktop"

  # remove unused files
  rm -rf "${pkgdir}/usr/share/spotify/apt-keys"
  rm -rf "${pkgdir}/usr/share/doc/spotify-client"

  # setup icons
  mkdir -p "${pkgdir}/usr/share/pixmaps"

  for size in 22 24 32 48 64 128 256 512; do
    mkdir -p "${pkgdir}/usr/share/icons/hicolor/${size}x${size}/apps/"
    ln -sf "/usr/share/spotify/icons/spotify-linux-${size}.png" \
      "${pkgdir}/usr/share/icons/hicolor/${size}x${size}/apps/spotify-client.png"
  done

  ln -sf '/usr/lib/libcurl.so.4' "${pkgdir}/usr/share/spotify/libcurl-gnutls.so.4"

  # use custom launcher
  rm -f "${pkgdir}/usr/bin/spotify"
  cp "${srcdir}/launcher.sh" "${pkgdir}/usr/bin/spotify"
  chmod +x "${pkgdir}/usr/bin/spotify"
}

