#!/bin/bash

SELF_SRC="$(realpath ${BASH_SOURCE})"
SELF_DIR="$(dirname "${SELF_SRC}")"

function guard() {
  local code="${1}"
  local message="${2}"

  if [ "${code}" -ne 0 ]; then
    echo "${message} (${code})"
    exit 1
  fi
}

function switch() {
  local user="${1}"
  local group="${2}"

  if [ "${user}" != "$(whoami)" ]; then
    exec su -g "${group}" -m -s '/bin/bash' "${user}" -- "${SELF_SRC}" "${@:3}"
  fi
}

function install() {
  local srcdir="${SELF_DIR}/srcpkgs/${1}"

  test -f "${srcdir}/template"
  guard $? 'no teamplate file found'

  # skip dependency install if not running as root
  test "$(whoami)" != 'root' && return 1

  ( source "${srcdir}/template"
    test -n "${makedepends[*]}" && xbps-install -Ay ${makedepends[*]}
  )
}

function build() {
  local keydir="${SELF_DIR}"
  local pkgdir="${SELF_DIR}/pkgdir"
  local bindir="${SELF_DIR}/binpkgs"
  local srcdir="${SELF_DIR}/srcpkgs/${1}"

  test -f "${srcdir}/template"
  guard $? 'no teamplate file found'

  find "${pkgdir}" -mindepth 1 -delete
  mkdir -p "${pkgdir}"

  ( source "${srcdir}/template"

    # run prepare steps from template file
    ( set -e; prepare )
    guard $? 'error in prepare step'

    # run package steps from template file
    ( set -e; package )
    guard $? 'error in package step'

    mkdir -p "${bindir}/${arch}"

    # required to "overwrite" signature of same package version
    # this also requires deletion of /var/cache/xbps/<pkgname>.{xbps,sig} on clients
    rm -f "${bindir}/${arch}/${pkgname}-${version}_${revision}.${arch}.xbps.sig"

    cd "${bindir}/${arch}"
    xbps-create "${pkgdir}" \
      -n "${pkgname}-${version}_${revision}" \
      -A "${arch}" \
      -D "${depends[*]}" \
      -H "${homepage}" \
      -l "${license}" \
      -s "${short_desc}"

    export XBPS_TARGET_ARCH="${arch}"
    xbps-rindex -c "${bindir}/${arch}"
    xbps-rindex -f -a "${bindir}/${arch}"/*.xbps
    xbps-rindex "${bindir}/${arch}" \
      --sign --signedby 'root <root@raspberry.home>' \
      --privkey "${keydir}/signkey.pem"
    xbps-rindex \
      --sign-pkg "${bindir}/${arch}/${pkgname}-${version}_${revision}.${arch}.xbps" \
      --privkey "${keydir}/signkey.pem"
  )

  # do not purge package directory when build fails (for debugging purposes)
  if [ $? -eq 0 ]; then
    find "${pkgdir}" -mindepth 1 -delete
  fi
}

function main() {
  install "${@}"
  switch 'nobody' 'xbuilder' "${@}"
  build "${@}"
}

main "${@}"

