#!/bin/bash

SELF_SRC="$(realpath ${BASH_SOURCE})"
SELF_DIR="$(dirname "${SELF_SRC}")"

function switch() {
  local user="${1}"
  local group="${2}"

  if [ "${user}" != "$(whoami)" ]; then
    exec su -g "${group}" -m -s '/bin/bash' "${user}" -- "${SELF_SRC}" "${@:3}";
  fi
}

function guard() {
  local code="${1}"
  local message="${2}"

  if [ "${code}" -ne 0 ]; then
    echo "${message} (${code})"
    exit 1
  fi
}

function build() {
  local keydir="${SELF_DIR}"
  local pkgdir="${SELF_DIR}/pkgdir"
  local bindir="${SELF_DIR}/binpkgs"
  local srcdir="${SELF_DIR}/srcpkgs/${1}"

  [ -f "${srcdir}/template" ]
  guard $? 'no teamplate file found'

  source "${srcdir}/template"

  rm -rf "${pkgdir}"
  mkdir -p "${pkgdir}"

  # runs steps from template file
  ( set -e; prepare )
  guard $? 'error in prepare step'

  ( set -e; package )
  guard $? 'error in package step'

  ( # runs in a subshell
    mkdir -p "${bindir}/${arch}"
    cd "${bindir}/${arch}"
    xbps-create "${pkgdir}" \
      -n "${pkgname}-${version}_${revision}" \
      -A "${arch}" \
      -D "${depends[*]}" \
      -H "${homepage}" \
      -l "${license}" \
      -s "${short_desc}"

    export XBPS_TARGET_ARCH="${arch}"
    xbps-rindex -c "${bindir}/${arch}"
    xbps-rindex -f -a "${bindir}/${arch}"/*.xbps
    xbps-rindex "${bindir}/${arch}" \
      --sign --signedby 'root <root@raspberry.home>' \
      --privkey "${keydir}/signkey.pem"
    xbps-rindex \
      --sign-pkg "${bindir}/${arch}/${pkgname}-${version}_${revision}.${arch}.xbps" \
      --privkey "${keydir}/signkey.pem"
  )

  rm -rf "${pkgdir}"
}

function main() {
  switch 'nobody' 'xbuilder' "${@}"
  build "${@}"
}

main "${@}"

