#!/bin/bash

SELF_SRC="$(realpath ${BASH_SOURCE})"
SELF_DIR="$(dirname "${SELF_SRC}")"

function switch() {
  local user="${1}"
  local group="${2}"

  if [ "${user}" != "$(whoami)" ]; then
    exec su -g "${group}" -m -s '/bin/bash' "${user}" -- "${SELF_SRC}" "${@:3}"
  fi
}

function chroot() {
  local tmpdir="${1}"

  if [ ! -f '/.chroot' ]; then
    mkdir -p "${tmpdir}"/{rootfs,buildfs}
    umount -qR "${tmpdir}/rootfs"

    mount -t overlay overlay -o lowerdir=/,upperdir="${tmpdir}/buildfs",workdir="${tmpdir}/rootfs" "${tmpdir}/rootfs"
    mount -t proc /proc "${tmpdir}/rootfs/proc/"
    mount -t sysfs /sys "${tmpdir}/rootfs/sys/"
    mount --rbind /dev "${tmpdir}/rootfs/dev/"
    mount --rbind /run "${tmpdir}/rootfs/run/"
    mount --bind "${SELF_DIR}" "${tmpdir}/rootfs/${SELF_DIR}"

    touch "${tmpdir}/rootfs/.chroot"
    exec chroot "${tmpdir}/rootfs" '/bin/bash' -- "${SELF_SRC}" "${@:2}"
  fi
}

function guard() {
  local code="${1}"
  local message="${2}"

  if [ "${code}" -ne 0 ]; then
    echo "${message} (${code})"
    exit 1
  fi
}

function build() {
  local keydir="${SELF_DIR}"
  local pkgdir="${SELF_DIR}/pkgdir"
  local bindir="${SELF_DIR}/binpkgs"
  local srcdir="${SELF_DIR}/srcpkgs/${1}"

  [ -f "${srcdir}/template" ]
  guard $? 'no teamplate file found'

  source "${srcdir}/template"

  if [ "$(whoami)" == 'root' ]; then
    test -z "${makedepends[*]}" || xbps-install -Ay ${makedepends[*]}
    switch 'nobody' 'xbuilder' "${@}"
  fi

  find "${pkgdir}" -mindepth 1 -delete
  mkdir -p "${pkgdir}"

  # runs steps from template file
  ( set -e; prepare )
  guard $? 'error in prepare step'

  ( set -e; package )
  guard $? 'error in package step'

  (
    mkdir -p "${bindir}/${arch}"

    # required to "overwrite" signature of same package version
    # this also requires deletion of /var/cache/xbps/<pkgname>.{xbps,sig} on clients
    rm -f "${bindir}/${arch}/${pkgname}-${version}_${revision}.${arch}.xbps.sig"

    cd "${bindir}/${arch}"
    xbps-create "${pkgdir}" \
      -n "${pkgname}-${version}_${revision}" \
      -A "${arch}" \
      -D "${depends[*]}" \
      -H "${homepage}" \
      -l "${license}" \
      -s "${short_desc}"

    export XBPS_TARGET_ARCH="${arch}"
    xbps-rindex -c "${bindir}/${arch}"
    xbps-rindex -f -a "${bindir}/${arch}"/*.xbps
    xbps-rindex "${bindir}/${arch}" \
      --sign --signedby 'root <root@raspberry.home>' \
      --privkey "${keydir}/signkey.pem"
    xbps-rindex \
      --sign-pkg "${bindir}/${arch}/${pkgname}-${version}_${revision}.${arch}.xbps" \
      --privkey "${keydir}/signkey.pem"
  )

  rm -rf "${pkgdir}"
}

function main() {
  chroot '/tmp/xbps-src' "${@}"
  build "${@}"
}

main "${@}"

