#!/bin/bash

pkgname='nginx-dav-ext-module'
version='3.0.0'
revision='9'
arch='armv7l'

#makdepends=('gcc' 'make' 'perl' 'geoip-devel' 'libxml2-devel' 'libxslt-devel' 'openssl-devel' 'pcre-devel')
depends=('nginx>=1.24.0_1 libxml2>=2.9.10_1 libxslt>=1.1.34_1')

short_desc='nginx module with support for missing PROPFIND and OPTIONS WebDAV methods'
license='CUSTOM'
homepage='https://github.com/arut/nginx-dav-ext-module'

prepare() {
  # downloads source archive
  [ -f "${srcdir}/sources.zip" ] || curl \
    -o "${srcdir}/sources.zip" \
    -L "https://github.com/arut/nginx-dav-ext-module/archive/refs/tags/v${version}.zip"

  [ -f "${srcdir}/sources.tar.gz" ] || curl \
    -o "${srcdir}/sources.tar.gz" \
    -L "https://nginx.org/download/nginx-1.24.0.tar.gz"
}

package() {
  tar --extract -C "${pkgdir}" -vf "${srcdir}/sources.tar.gz"
  unzip -d "${pkgdir}/nginx-"* "${srcdir}/sources.zip"

  cd "${pkgdir}/nginx-"*

  ./configure --add-dynamic-module="nginx-dav-ext-module-"* \
    --with-compat \
    --with-http_dav_module \
    $(2>&1 nginx -V | grep -oP -- '--\S+' | grep -vE -- '--(add-dynamic-module|with)' | paste -sd ' ')

  make modules

  cd 'objs'
  for module in *.so; do
    install -Dm 755 "${module}" "${pkgdir}/usr/lib/nginx/modules/${module}"
  done

  rm -rf "${pkgdir}/nginx-"*
}

