#!/bin/bash

pkgname='teams'
version='1.3.14'
revision='2'
arch='x86_64'

depends=()

short_desc='Microsoft Teams for Linux'
license='Proprietary'
homepage='https://teams.microsoft.com'

prepare() {
  # downloadis bundle
  [ -f "${srcdir}/bundle.tar.gz" ] || curl \
    -o "${srcdir}/bundle.tar.gz" \
    -L "https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v${version}/teams-for-linux-${version}.tar.gz"
}

package() {
  # extract bundle
  mkdir -p "${pkgdir}/usr/lib/teams"
  tar --extract -C "${pkgdir}/usr/lib/teams" -vf "${srcdir}/bundle.tar.gz" \
    --strip-components=1

  # use custom launcher
  mkdir -p "${pkgdir}/usr/bin"
  cp "${srcdir}/launcher.sh" "${pkgdir}/usr/bin/teams"
  chmod +x "${pkgdir}/usr/bin/teams"


  mkdir -p "${pkgdir}/usr/share/applications"
  install -Dm 644 "${srcdir}/teams.desktop" "${pkgdir}/usr/share/applications"

  # download icons
  for size in 24 32 48 64 128 256 512; do
    mkdir -p "${pkgdir}/usr/share/icons/hicolor/${size}x${size}/apps/"
    curl -L "https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/build/icons/${size}x${size}.png?raw=true" \
      -o "${pkgdir}/usr/share/icons/hicolor/${size}x${size}/apps/teams.png"
  done
}

