#!/bin/bash

# official void-packages teamplate:
# https://github.com/void-linux/void-packages/blob/master/srcpkgs/teamspeak3/template

pkgname='teamspeak3'
version='3.5.6'
revision='2'
arch='x86_64'
depends='libxslt>=1.1.34 alsa-lib>=1.2.4 libXi>=1.7.10'

short_desc='Popular proprietary voice chat for gaming'
license='Proprietary'
homepage='https://www.teamspeak.com'

prepare() {
  # downloads teamspeak3 bundle
  [ -f "${srcdir}/installer.run" ] || curl \
    -o "${srcdir}/installer.run" \
    -L "https://files.teamspeak-services.com/releases/client/${version}/TeamSpeak3-Client-linux_amd64-${version}.run"
}

package() {
  mkdir -p "${pkgdir}/usr/bin"
  mkdir -p "${pkgdir}/usr/lib/teamspeak3"
  mkdir -p "${pkgdir}/usr/share/applications"
  mkdir -p "${pkgdir}/usr/share/icons/hicolor/256x256/apps"

  sh "${srcdir}/installer.run" --tar xfC "${pkgdir}/usr/lib/teamspeak3"

  find "${pkgdir}" -type d | xargs chmod 755
  find "${pkgdir}" -type f | xargs chmod 644
  find "${pkgdir}" -name '*.so*' | xargs chmod 755

  chmod +x "${pkgdir}/usr/lib/teamspeak3/"{ts3client,package_inst,QtWebEngineProcess}*

  install -Dm 644 "${srcdir}/teamspeak3.desktop" "${pkgdir}/usr/share/applications"
  install -Dm 644 "${srcdir}/logo.png" "${pkgdir}/usr/share/icons/hicolor/256x256/apps/teamspeak3.png"

  ln -sf "${pkgdir}/usr/lib/teamspeak3/ts3client_runscript.sh" '/usr/bin/teamspeak3'
}

