#!/bin/bash

pkgname='wine-lol'
version='7.0'
revision='4'
arch='x86_64'

#makdepends=(
#  'autoconf' 'bison' 'flex' 'make' 'patch' 'pkg-config'
#  'gcc' 'gcc-multilib' 'libgcc-devel-32bit'
#  'fontconfig-devel-32bit' 'freetype-devel-32bit'
#  'libpng-devel-32bit' 'libjpeg-turbo-devel-32bit'
#  'libxml2-devel-32bit' 'libXcursor-devel-32bit'
#  'libXrandr-devel-32bit' 'libXdamage-devel-32bit'
#  'libXi-devel-32bit' 'libSM-devel-32bit'
#  'FAudio-devel-32bit' 'mpg123-devel-32bit' 'pulseaudio-devel'
#  'vkd3d-devel-32bit' 'Vulkan-Headers'
#  'gstreamer1-devel-32bit' 'gst-plugins-base1-devel-32bit'
#  'gnutls-devel-32bit' 'libgcrypt-devel-32bit')

depends=(
  'fontconfig>=2.13.1_1' 'fontconfig-32bit>=2.13.1_1'
  'freetype>=2.10.4_1' 'freetype-32bit>=2.10.4_1'
  'libpng>=1.6.37_1' 'libpng-32bit>=1.6.37_1'
  'libjpeg-turbo>=2.1.1_1' 'libjpeg-turbo-32bit>=2.1.1_1'
  'libxml2>=2.9.10_5' 'libxml2-32bit>=2.9.10_5'
  'libXcursor>=1.2.0_1' 'libXcursor-32bit>=1.2.0_1'
  'libXrandr>=1.5.2_1' 'libXrandr-32bit>=1.5.2_1'
  'libXdamage>=1.1.5_1' 'libXdamage-32bit>=1.1.5_1'
  'libXi>=1.7.10_1' 'libXi-32bit>=1.7.10_1'
  'libSM>=1.2.3_1' 'libSM-32bit>=1.2.3_1'
  'libgcc>=10.2.1pre1_1' 'libgcc-32bit>=10.2.1pre1_1'
  'FAudio>=20.11_1' 'FAudio-32bit>=20.11_1'
  'libmpg123>=1.28.2_1' 'libmpg123-32bit>=1.28.2_1'
  'libpulseaudio>=15.0_1' 'libpulseaudio-32bit>=15.0_1'
  'vulkan-loader>=1.2.182_1' 'vulkan-loader-32bit>=1.2.182_1'
  'vkd3d>=1.2_1' 'vkd3d-32bit>=1.2_1'
  'gstreamer1>=1.18.4_1' 'gstreamer1-32bit>=1.18.4_1'
  'gst-plugins-base1>=1.18.4_1' 'gst-plugins-base1-32bit>=1.18.4_1'
  'gnutls>=3.6.16_1' 'gnutls-32bit>=3.6.16_1'
  'libgcrypt>=1.9.4_1' 'libgcrypt-32bit>=1.9.4_1'
  'desktop-file-utils>=0.26_1')

short_desc='A compatibility layer for running Windows programs - Staging branch with League of Legends fixes and GloriousEggroll patches'
license='LGPL'
homepage='https://www.winehq.com'

prepare() {
  # downloads bundle
  [ -f "${srcdir}/bundle.tar.xz" ] || curl \
    -o "${srcdir}/bundle.tar.xz" \
    -L "https://github.com/GloriousEggroll/wine-ge-custom/releases/download/${version}-GE-${revision}-LoL/wine-lutris-ge-lol-${version}-${revision}-x86_64.tar.xz"
}

package() {
  tar --extract -C "${pkgdir}" -vf "${srcdir}/bundle.tar.xz"

  mkdir -p "${pkgdir}/opt/wine-lol"
  mv "${pkgdir}/lutris-ge-"*/* "${pkgdir}/opt/wine-lol"
}

