#!/bin/bash

pkgname='xp-pen-tablet'
version='3.1.4'
revision='1'
arch='x86_64'

depends=()

short_desc='XP-Pen (Official) Linux utility (New UI driver)'
license='GPL'
homepage='https://www.xp-pen.com'

prepare() {
  # downloads bundle
  [ -f "${srcdir}/bundle.tar.gz" ] || curl \
    -o "${srcdir}/bundle.tar.gz" \
    -L "https://download01.xp-pen.com/file/2021/07/XP-PEN-pentablet-3.1.4.210623-1.x86_64.tar.gz"
}

package() {
  tar --extract -C "${pkgdir}" -vf "${srcdir}/bundle.tar.gz"

  mkdir -p "${pkgdir}/usr/lib/"
  mv "${pkgdir}/xp-pen-pentablet"*/"App/usr"/* "${pkgdir}/usr/"
  mv "${pkgdir}/xp-pen-pentablet-"*/"App/lib"/* "${pkgdir}/usr/lib/"

  cp "${srcdir}/pentablet.sh" "${pkgdir}/usr/lib/pentablet/pentablet.sh"
  chmod +x "${pkgdir}/usr/lib/pentablet/pentablet.sh"

  rm -rf "${pkgdir}/xp-pen-pentablet-"*
}

