#!/bin/bash

pkgname='rtl8188eu'
version='5.4.83'
revision='1'
arch='armv7l'
depends=''

short_desc='Kernel module for rtl8188eu'
license='Proprietary'
homepage='https://github.com/lwfinger/rtl8188eu'

prepare() {
  # downloads source archive
  [ -f "${srcdir}/sources.zip" ] || curl \
    -o "${srcdir}/sources.zip" \
    -L 'https://github.com/lwfinger/rtl8188eu/archive/v5.2.2.4.zip'
}

package() {
  unzip -d "${pkgdir}" "${srcdir}/sources.zip"

  cd "${pkgdir}/rtl8188eu-"*
  mkdir .git

  make KVER="$(uname -r)" all

  mkdir -p "${pkgdir}/etc/modprobe.d"
  mkdir -p "${pkgdir}/usr/lib/modules/${kernel}/kernel/drivers/net/wireless"
  mkdir -p "${pkgdir}/usr/lib/firmware/rtlwifi"

  install -Dm 644 "${pkgdir}/rtl8188eu-"*/8188eu.ko "${pkgdir}/usr/lib/modules/${kernel}/kernel/drivers/net/wireless"
  install -Dm 644 "${pkgdir}/rtl8188eu-"*/rtl8188eufw.bin "${pkgdir}/usr/lib/firmware/rtlwifi"

  echo 'blacklist r8188eu' > "${pkgdir}/etc/modprobe.d/50-8188eu.conf"

  rm -rf "${pkgdir}/rtl8188eu-"*
}

