#!/bin/bash

pkgname='rtl8188eu'
version='5.2.2.4'
revision='2'
arch='armv7l'

#makedepends=(gcc make flex rpi2-kernel rpi2-kernel-headers openssl-devel)
depends='rpi2-kernel>=5.10.52_1'

short_desc='Kernel module for rtl8188eu'
license='Proprietary'
homepage='https://github.com/lwfinger/rtl8188eu'

prepare() {
  # downloads source archive
  [ -f "${srcdir}/sources.zip" ] || curl \
    -o "${srcdir}/sources.zip" \
    -L 'https://github.com/lwfinger/rtl8188eu/archive/v5.2.2.4.zip'
}

package() {
  unzip -d "${pkgdir}" "${srcdir}/sources.zip"

  # use first kernel version in modules folder
  cd '/lib/modules'
  for kernel in *; do break; done

  if [ -z "${kernel}" ]; then
    echo 'Could not get target kernel version'
    exit 1
  fi

  cd "${pkgdir}/rtl8188eu-"*
  mkdir .git

  make KVER="${kernel}" all

  install -Dm 644 "${pkgdir}/rtl8188eu-"*/8188eu.ko "${pkgdir}/usr/lib/modules/${kernel}/kernel/drivers/net/wireless/8188eu.ko"
  install -Dm 644 "${pkgdir}/rtl8188eu-"*/rtl8188eufw.bin "${pkgdir}/usr/lib/firmware/rtlwifi/rtl8188eufw.bin"
  install -Dm 644 "${srcdir}/blacklist.conf" "${pkgdir}/etc/modprobe.d/blacklist-r8188eu.conf"

  rm -rf "${pkgdir}/rtl8188eu-"*
}

