#!/bin/bash

pkgname='nginx-fancy-index-module'
version='0.5.2'
revision='3'
arch='armv7l'

makedepends=('gcc' 'make' 'perl' 'geoip-devel' 'libxml2-devel' 'libxslt-devel' 'openssl-devel' 'pcre-devel')
depends=('nginx>=1.22.0_3')

short_desc='nginx module to customize look and feel of directory listings'
license='CUSTOM'
homepage='https://github.com/aperezdc/ngx-fancyindex'

prepare() {
  # downloads source archive
  [ -f "${srcdir}/sources.zip" ] || curl \
    -o "${srcdir}/sources.zip" \
    -L "https://github.com/aperezdc/ngx-fancyindex/archive/refs/tags/v${version}.zip"

  [ -f "${srcdir}/sources.tar.gz" ] || curl \
    -o "${srcdir}/sources.tar.gz" \
    -L "https://nginx.org/download/nginx-1.22.0.tar.gz"
}

package() {
  tar --extract -C "${pkgdir}" -vf "${srcdir}/sources.tar.gz"
  unzip -d "${pkgdir}/nginx-"* "${srcdir}/sources.zip"

  cd "${pkgdir}/nginx-"*

  ./configure --add-dynamic-module="ngx-fancyindex-"* \
    --with-compat \
    $(2>&1 nginx -V | grep -oP -- '--\S+' | grep -vE -- '--(add-dynamic-module|with)' | paste -sd ' ')

  make modules

  cd 'objs'
  for module in *.so; do
    install -Dm 755 "${module}" "${pkgdir}/usr/lib/nginx/modules/${module}"
  done

  rm -rf "${pkgdir}/nginx-"*
}

